apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xfn-api
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xfn-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xfn-api
subjects:
  - kind: ServiceAccount
    name: xfn-api
    namespace: "crossplane-system"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xfn-api
  namespace: "crossplane-system"
