apiVersion: v1
kind: Service
metadata:
  name: xfn-api
  namespace: "crossplane-system"
spec:
  selector:
    app: xfn-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
